project:
  type: website

website:
  title: "Koen Hufkens"
  site-url: https://khufkens.com
  open-graph: true
  twitter-card:
    creator: "@koen_hufkens@mastodon.social"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: github
        href: https://github.com/bluegreen-labs/
      - icon: mastodon
        href: https://mastodon.social/@koen_hufkens
      - icon: rss
        href: index.xml
format:
  html:
    theme: litera
    css: styles.css

editor: visual
